---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Hyunje Park
thanks: "Code and data are available at: [https://github.com/davidpxrk/childrens-book-rating](https://github.com/davidpxrk/childrens-book-rating)."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
library(kableExtra)
library(arrow)
library(readr)
library(rstanarm)
library(modelsummary)

data <- read_parquet(here::here("data/analysis_data/analysis_data.parquet"))
print(data)
```


# Introduction



```{r}
#| label: cleaned_dataset-preview
#| fig-cap: "Preview of the Cleaned Dataset"
#| echo: false

# TABLE 1: CLEANED DATASET
data %>% head(5)
```


```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false

data %>% 
  select(-c(title)) %>% 
  summary(rated-high) %>% 
  kable(booktabs = TRUE, linesep = "") %>% 
  kable_styling(position = "left", bootstrap_options = "condensed", full_width = FALSE)


```


# Data {#sec-data}

```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false


data2 <- data %>% filter(rating > 4 )

ggplot(data2, aes(x = publish_year, y = rating)) +
  geom_point() +
  theme_minimal()


ggplot(data2, aes(x = rating, y = rating_count)) +
  geom_point() +
  geom_smooth( se =FALSE, color = "red", size = 1)

ggplot(data2, aes(x = rating, y = pages)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = 'red', size = 1)

ggplot(data2, aes(y = cover)) + 
  geom_bar() +
  theme_minimal()


avg_pages <- aggregate(pages ~ rated_high, data = data, FUN = mean, na.rm = TRUE)


ggplot(avg_pages, aes(x = factor(rated_high), y = pages, fill = factor(rated_high))) +
  geom_bar(stat = "identity") +
  labs(
    title = "Average Pages by High Rated",
    x = "High Rated (1 = Yes, 0 = No)",
    y = "Average Pages",
    fill = "High Rated"
  ) +
  theme_minimal()


cover_counts <- data %>%
  group_by(rated_high, cover) %>%
  summarise(count = n()) %>%
  ungroup()

ggplot(cover_counts, aes(x = cover, y = count, fill = cover)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ rated_high) +
  labs(title = "Count of Hardcover and Paperback by Rated High",
       x = "Cover Type",
       y = "Count") +
  theme_minimal()




```



\newpage
```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false

model_file <- readRDS(file = here::here("models/model.rds"))

modelsummary(
  list (
    "Book is High-Rated" = model_file
  ),
  statistic = "mad"
)

```

```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false

pp_check(model_file) +
  theme(legend.position = "bottom")


```

```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false

posterior_vs_prior(model_file, size = 0.3) +
   theme_minimal() +
   theme(legend.position = "bottom") +
   theme(axis.text.x=element_text(hjust=1, vjust=0.5),
         text=element_text(size=8)) +
   coord_flip()

```


```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false
#| fig-subcap: ["Intercept", "pages", "rating_count", "publish_year", "coverEbook", "coverKindle", "coverBoard", "coverHardcover", "coverPaperback"]
#| layout-ncol: 3

plot(model_file, "trace", "(Intercept)")
plot(model_file, "trace", "pages")
plot(model_file, "trace", "rating_count")
plot(model_file, "trace", "publish_year")
plot(model_file, "trace", "coverEbook")
plot(model_file, "trace", "coverKindle Edition")
plot(model_file, "trace", "coverBoard Book")
plot(model_file, "trace", "coverHardcover")
plot(model_file, "trace", "coverPaperback")


```



```{r}
#| label: summary_statistic_cleaned_dataset
#| fig-cap: "Summary Statistic of the Cleaned Dataset"
#| echo: false

plot(model_file, "rhat")

```
# References


